// headerStyles.js
export const header = {
  contactText: "Contact Us",
  contactBackgroundColor: "orange",
  contactBorder: "none",
  contactColor: "#fff",
  contactFontFamily: "Arial, sans-serif",
  contactFontWeight: "bold",
  contactHoverBorder: "1px solid #666",
  contactHoverColor: "#fff",
  hoverContactBackgroundColor: "yellow",
  contactHref: "#contact",
  contactTextDecoration: "none",
  contactTransition: "all 0.3s ease",
  gap: "20px",
  id: "main-header",
  backgroundColor: "#f0f0f0",
  fontSize: "16px",
  fontWeight: "bold",
  fontFamily: "Arial, sans-serif",
  textDecoration: "none",
  border: "none",
  color: "#333",
  hoverBackgroundColor: "#cccccc",
  hoverColor: "#fff",
  hoverBorder: "1px solid #666",
  transition: "all 0.3s ease",
  cursor: "pointer",
};
